# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_2d_peaks_c <- function(mz, rt, intensity, mz_ppm = 5.0, rt_window = 5, snr_threshold = 3.0, mz_bins = 100L, rt_bins = 100L) {
    .Call(`_sfi_find_2d_peaks_c`, mz, rt, intensity, mz_ppm, rt_window, snr_threshold, mz_bins, rt_bins)
}

